import { db } from "../../db";
import { linkedinMessages } from "@shared/schema";
import { eq, and, gte, lte, sql } from "drizzle-orm";

export async function getEngagementTrends(days: number, userId: number) {
  try { const startDate = new Date(); startDate.setDate(startDate.getDate() - days);
  const dailyStats = await db.select({ date: sql<string>`DATE(${linkedinMessages.sentAt})`, sent: sql<number>`COUNT(*)`, accepted: sql<number>`COUNT(CASE WHEN ${linkedinMessages.status} = 'accepted' THEN 1 END)`, replied: sql<number>`COUNT(CASE WHEN ${linkedinMessages.status} = 'replied' THEN 1 END)` }).from(linkedinMessages).where(and(eq(linkedinMessages.userId, userId), gte(linkedinMessages.sentAt, startDate))).groupBy(sql`DATE(${linkedinMessages.sentAt})`).orderBy(sql`DATE(${linkedinMessages.sentAt})`);
  return dailyStats.map(day => ({ date: day.date, sent: Number(day.sent) || 0, accepted: Number(day.accepted) || 0, replied: Number(day.replied) || 0, acceptanceRate: Number(day.sent) > 0 ? (Number(day.accepted) / Number(day.sent)) * 100 : 0, replyRate: Number(day.sent) > 0 ? (Number(day.replied) / Number(day.sent)) * 100 : 0 })); } catch (error) { console.error('[LinkedIn Analytics] Error getting engagement trends:', error); throw error; }
}

export async function getTrendComparison(userId: number, days: 7 | 30 = 7) {
  try { const currentPeriodEnd = new Date(); const currentPeriodStart = new Date(); currentPeriodStart.setDate(currentPeriodStart.getDate() - days); const previousPeriodEnd = new Date(currentPeriodStart); const previousPeriodStart = new Date(previousPeriodEnd); previousPeriodStart.setDate(previousPeriodStart.getDate() - days);
  const [currentStats] = await db.select({ totalSent: sql<number>`COUNT(*)`, accepted: sql<number>`COUNT(CASE WHEN ${linkedinMessages.status} = 'accepted' THEN 1 END)`, replied: sql<number>`COUNT(CASE WHEN ${linkedinMessages.status} = 'replied' THEN 1 END)` }).from(linkedinMessages).where(and(eq(linkedinMessages.userId, userId), gte(linkedinMessages.sentAt, currentPeriodStart), lte(linkedinMessages.sentAt, currentPeriodEnd)));
  const [previousStats] = await db.select({ totalSent: sql<number>`COUNT(*)`, accepted: sql<number>`COUNT(CASE WHEN ${linkedinMessages.status} = 'accepted' THEN 1 END)`, replied: sql<number>`COUNT(CASE WHEN ${linkedinMessages.status} = 'replied' THEN 1 END)` }).from(linkedinMessages).where(and(eq(linkedinMessages.userId, userId), gte(linkedinMessages.sentAt, previousPeriodStart), lte(linkedinMessages.sentAt, previousPeriodEnd)));
  const currentSent = Number(currentStats?.totalSent || 0); const currentAccepted = Number(currentStats?.accepted || 0); const currentReplied = Number(currentStats?.replied || 0); const previousSent = Number(previousStats?.totalSent || 0); const previousAccepted = Number(previousStats?.accepted || 0); const previousReplied = Number(previousStats?.replied || 0);
  const currentAcceptanceRate = currentSent > 0 ? (currentAccepted / currentSent) * 100 : 0; const currentReplyRate = currentSent > 0 ? (currentReplied / currentSent) * 100 : 0; const previousAcceptanceRate = previousSent > 0 ? (previousAccepted / previousSent) * 100 : 0; const previousReplyRate = previousSent > 0 ? (previousReplied / previousSent) * 100 : 0;
  return { periodDays: days, currentPeriod: { totalSent: currentSent, accepted: currentAccepted, replied: currentReplied, acceptanceRate: currentAcceptanceRate, replyRate: currentReplyRate }, previousPeriod: { totalSent: previousSent, accepted: previousAccepted, replied: previousReplied, acceptanceRate: previousAcceptanceRate, replyRate: previousReplyRate }, deltas: { sent: currentSent - previousSent, sentPercentChange: previousSent > 0 ? ((currentSent - previousSent) / previousSent) * 100 : 0, acceptanceRate: currentAcceptanceRate - previousAcceptanceRate, replyRate: currentReplyRate - previousReplyRate }, hasPreviousPeriodData: previousSent > 0 }; } catch (error) { console.error('[LinkedIn Analytics] Error getting trend comparison:', error); throw error; }
}
