import type { Request, Response } from "express";
import { eq, and } from "drizzle-orm";
import { db } from "../../db";
import { followUpSequences } from "@shared/schema";

export async function createSequence(req: Request, res: Response) { try { const userId = req.session.userId; if (!userId) return res.status(401).json({ error: 'Unauthorized' }); const sequenceData = { userId, name: req.body.name, description: req.body.description || '', active: req.body.active !== undefined ? req.body.active : true, stopOnReply: req.body.stopOnReply !== undefined ? req.body.stopOnReply : true, stopOnOpen: req.body.stopOnOpen || false, stopOnClick: req.body.stopOnClick || false, stopOnMeeting: req.body.stopOnMeeting !== undefined ? req.body.stopOnMeeting : true }; const [newSequence] = await db.insert(followUpSequences).values(sequenceData).returning(); res.json(newSequence); } catch (error: any) { console.error('Error creating sequence:', error); res.status(500).json({ error: 'Failed to create sequence' }); } }

export async function updateSequence(req: Request, res: Response) { try { const userId = req.session.userId; if (!userId) return res.status(401).json({ error: 'Unauthorized' }); const sequenceId = parseInt(req.params.id); const updateData: any = {}; if (req.body.name !== undefined) updateData.name = req.body.name; if (req.body.description !== undefined) updateData.description = req.body.description; if (req.body.active !== undefined) updateData.active = req.body.active; if (req.body.stopOnReply !== undefined) updateData.stopOnReply = req.body.stopOnReply; if (req.body.stopOnOpen !== undefined) updateData.stopOnOpen = req.body.stopOnOpen; if (req.body.stopOnClick !== undefined) updateData.stopOnClick = req.body.stopOnClick; if (req.body.stopOnMeeting !== undefined) updateData.stopOnMeeting = req.body.stopOnMeeting; const [updatedSequence] = await db.update(followUpSequences).set(updateData).where(and(eq(followUpSequences.id, sequenceId), eq(followUpSequences.userId, userId))).returning(); if (!updatedSequence) return res.status(404).json({ error: 'Sequence not found' }); res.json(updatedSequence); } catch (error: any) { console.error('Error updating sequence:', error); res.status(500).json({ error: 'Failed to update sequence' }); } }

export async function deleteSequence(req: Request, res: Response) { try { const userId = req.session.userId; if (!userId) return res.status(401).json({ error: 'Unauthorized' }); const sequenceId = parseInt(req.params.id); const [deleted] = await db.delete(followUpSequences).where(and(eq(followUpSequences.id, sequenceId), eq(followUpSequences.userId, userId))).returning(); if (!deleted) return res.status(404).json({ error: 'Sequence not found' }); res.json({ success: true }); } catch (error: any) { console.error('Error deleting sequence:', error); res.status(500).json({ error: 'Failed to delete sequence' }); } }
