import type { Request, Response } from "express";
import { eq, and } from "drizzle-orm";
import { db } from "../../db";
import { followUpSequences, sequenceSteps } from "@shared/schema";

async function verifySequenceOwnership(sequenceId: number, userId: number): Promise<boolean> { const [sequence] = await db.select().from(followUpSequences).where(and(eq(followUpSequences.id, sequenceId), eq(followUpSequences.userId, userId))).limit(1); return !!sequence; }

export async function addStep(req: Request, res: Response) { try { const userId = req.session.userId; if (!userId) return res.status(401).json({ error: 'Unauthorized' }); const sequenceId = parseInt(req.params.id); if (!await verifySequenceOwnership(sequenceId, userId)) return res.status(404).json({ error: 'Sequence not found' }); const stepData = { sequenceId, stepNumber: req.body.stepNumber, delayDays: req.body.delayDays, subject: req.body.subject || '', body: req.body.body, variantName: req.body.variantName || 'A' }; const [newStep] = await db.insert(sequenceSteps).values(stepData).returning(); res.json(newStep); } catch (error: any) { console.error('Error adding sequence step:', error); res.status(500).json({ error: 'Failed to add sequence step' }); } }

export async function updateStep(req: Request, res: Response) { try { const userId = req.session.userId; if (!userId) return res.status(401).json({ error: 'Unauthorized' }); const sequenceId = parseInt(req.params.sequenceId); const stepId = parseInt(req.params.stepId); if (!await verifySequenceOwnership(sequenceId, userId)) return res.status(404).json({ error: 'Sequence not found' }); const updateData: any = {}; if (req.body.stepNumber !== undefined) updateData.stepNumber = req.body.stepNumber; if (req.body.delayDays !== undefined) updateData.delayDays = req.body.delayDays; if (req.body.subject !== undefined) updateData.subject = req.body.subject; if (req.body.body !== undefined) updateData.body = req.body.body; if (req.body.variantName !== undefined) updateData.variantName = req.body.variantName; const [updatedStep] = await db.update(sequenceSteps).set(updateData).where(and(eq(sequenceSteps.id, stepId), eq(sequenceSteps.sequenceId, sequenceId))).returning(); if (!updatedStep) return res.status(404).json({ error: 'Step not found' }); res.json(updatedStep); } catch (error: any) { console.error('Error updating sequence step:', error); res.status(500).json({ error: 'Failed to update sequence step' }); } }

export async function deleteStep(req: Request, res: Response) { try { const userId = req.session.userId; if (!userId) return res.status(401).json({ error: 'Unauthorized' }); const sequenceId = parseInt(req.params.sequenceId); const stepId = parseInt(req.params.stepId); if (!await verifySequenceOwnership(sequenceId, userId)) return res.status(404).json({ error: 'Sequence not found' }); const [deleted] = await db.delete(sequenceSteps).where(and(eq(sequenceSteps.id, stepId), eq(sequenceSteps.sequenceId, sequenceId))).returning(); if (!deleted) return res.status(404).json({ error: 'Step not found' }); res.json({ success: true }); } catch (error: any) { console.error('Error deleting sequence step:', error); res.status(500).json({ error: 'Failed to delete sequence step' }); } }
