import type { IcpProfile } from './types';

export function generateSuggestionsFromProfile(profile: IcpProfile | null): Array<{ description: string; filters: { jobTitles: string[]; industries: string[]; companySizes: string[]; locations: string[] }; predictedScore: number; reasoning: string }> {
  if (!profile || profile.icpConfidence < 0.3) return []; const suggestions: Array<{ description: string; filters: { jobTitles: string[]; industries: string[]; companySizes: string[]; locations: string[] }; predictedScore: number; reasoning: string }> = [];
  if (profile.bestPerformingAttributes.topTitles.length > 0) { suggestions.push({ description: `${profile.bestPerformingAttributes.topTitles[0]}s who respond well`, filters: { jobTitles: profile.bestPerformingAttributes.topTitles.slice(0, 3), industries: profile.bestPerformingAttributes.topIndustries.slice(0, 2), companySizes: profile.bestPerformingAttributes.topCompanySizes.slice(0, 2), locations: profile.bestPerformingAttributes.topLocations.slice(0, 3) }, predictedScore: Math.min(95, 70 + profile.icpConfidence * 25), reasoning: `Based on your ${(profile.bestPerformingAttributes.averageReplyRate * 100).toFixed(0)}% reply rate with similar leads` }); }
  const topIndustry = profile.industryPreferences.find(p => p.weight > 0.3); if (topIndustry) { suggestions.push({ description: `Decision makers in ${topIndustry.value}`, filters: { jobTitles: ['Director', 'VP', 'Manager', 'Owner'], industries: [topIndustry.value], companySizes: profile.bestPerformingAttributes.topCompanySizes.slice(0, 2), locations: [] }, predictedScore: 65 + topIndustry.weight * 20, reasoning: `${topIndustry.value} shows ${((0.5 + topIndustry.weight) * 100).toFixed(0)}% higher engagement` }); }
  if (profile.titlePreferences.length > 3) { const expandedTitles = profile.titlePreferences.filter(p => p.weight > 0).slice(0, 6).map(p => p.value); suggestions.push({ description: 'Expand to similar high-performing roles', filters: { jobTitles: expandedTitles, industries: [], companySizes: [], locations: [] }, predictedScore: 60, reasoning: 'These roles have similar engagement patterns to your best performers' }); }
  return suggestions;
}
