import type { Request, Response } from 'express';
import { getWarmupStatus, getWarmupSettings, setWarmupEnabled, setWarmupManualOverride, resetWarmup, getWarmupStages } from '../../deliverability/email-warmup';

export async function handleWarmupStatus(req: any, res: Response) { try { const userId = String(req.session.userId); const status = await getWarmupStatus(userId); res.json(status); } catch (error) { console.error('[Warmup] Status check error:', error); res.status(500).json({ error: 'Failed to get warm-up status' }); } }
export async function handleWarmupSettings(req: any, res: Response) { try { const userId = String(req.session.userId); const settings = await getWarmupSettings(userId); res.json(settings); } catch (error) { console.error('[Warmup] Settings retrieval error:', error); res.status(500).json({ error: 'Failed to get warm-up settings' }); } }
export async function handleWarmupEnabled(req: any, res: Response) { try { const userId = String(req.session.userId); const { enabled } = req.body; if (typeof enabled !== 'boolean') return res.status(400).json({ error: 'enabled must be a boolean' }); await setWarmupEnabled(userId, enabled); const status = await getWarmupStatus(userId); console.log(`[Warmup] ${enabled ? 'Enabled' : 'Disabled'} for user ${userId}`); res.json(status); } catch (error) { console.error('[Warmup] Enable/disable error:', error); res.status(500).json({ error: 'Failed to update warm-up status' }); } }
export async function handleWarmupStage(req: any, res: Response) { try { const userId = String(req.session.userId); const { stage } = req.body; if (!stage || stage < 1 || stage > 5) return res.status(400).json({ error: 'Stage must be between 1 and 5' }); const stages = getWarmupStages(); const stageConfig = stages.find(s => s.stage === stage); if (!stageConfig) return res.status(400).json({ error: 'Invalid stage' }); await setWarmupManualOverride(userId, true, stageConfig.dailyLimit, stage); const status = await getWarmupStatus(userId); console.log(`[Warmup] Stage manually set to ${stage} (${stageConfig.dailyLimit} emails/day)`); res.json({ success: true, ...status }); } catch (error) { console.error('[Warmup] Stage setting error:', error); res.status(500).json({ error: 'Failed to set warmup stage' }); } }
export async function handleManualOverride(req: any, res: Response) { try { const userId = String(req.session.userId); const { override, customLimit } = req.body; if (typeof override !== 'boolean') return res.status(400).json({ error: 'override must be a boolean' }); if (override && (!customLimit || customLimit <= 0)) return res.status(400).json({ error: 'customLimit must be a positive number when override is true' }); await setWarmupManualOverride(userId, override, customLimit); const status = await getWarmupStatus(userId); console.log(`[Warmup] Manual override: ${override}, limit=${customLimit || 'N/A'}`); res.json(status); } catch (error) { console.error('[Warmup] Manual override error:', error); res.status(500).json({ error: 'Failed to set manual override' }); } }
export async function handleWarmupReset(req: any, res: Response) { try { const userId = String(req.session.userId); await resetWarmup(userId); const status = await getWarmupStatus(userId); console.log(`[Warmup] Reset to stage 1 for user ${userId}`); res.json(status); } catch (error) { console.error('[Warmup] Reset error:', error); res.status(500).json({ error: 'Failed to reset warm-up' }); } }
export function handleWarmupStages(req: Request, res: Response) { try { const stages = getWarmupStages(); res.json(stages); } catch (error) { console.error('[Warmup] Stages retrieval error:', error); res.status(500).json({ error: 'Failed to get warm-up stages' }); } }
