export const INDUSTRIES = {
  saas: { emphasis: ['integration', 'scalability', 'ROI', 'automation', 'efficiency'], metrics: ['MRR', 'churn rate', 'CAC', 'LTV', 'NPS', 'adoption rate'], tone: 'consultative_technical', conversionRate: '0.03-0.5%', triggers: ['Reduce churn by {%}', 'Scale from {current} to {target} users', 'Integrate with your existing {tool} stack'], avoidTerms: ['revolutionary', 'game-changing', 'disruptive'], specialConsiderations: ['Focus on integration capabilities', 'Emphasize free trial/pilot', 'Show competitor comparisons'] },
  finance: { emphasis: ['compliance', 'security', 'accuracy', 'risk management', 'ROI'], metrics: ['ROI', 'risk reduction', 'processing time', 'error rate', 'compliance score'], tone: 'formal_authoritative', conversionRate: '1-2.5%', triggers: ['Reduce compliance risk by {%}', 'SEC/FINRA approved', 'Bank-grade security'], requirements: ['Include compliance certifications', 'Emphasize data security', 'Use precise numbers'], avoidTerms: ['guarantee', 'risk-free', 'insider'], formalityLevel: 'high' },
  ecommerce: { emphasis: ['conversion rate', 'revenue', 'customer experience', 'cart abandonment'], metrics: ['AOV', 'conversion rate', 'CAC', 'ROAS', 'cart abandonment rate'], tone: 'energetic_results_focused', conversionRate: '2.5-4.5%', triggers: ['Increase AOV by {%}', 'Recover {%} of abandoned carts', 'Boost holiday sales by {%}'], urgencyEffective: true, specialConsiderations: ['Show quick implementation', 'Focus on revenue impact', 'Include seasonal relevance'] },
  healthcare: { emphasis: ['patient outcomes', 'efficiency', 'compliance', 'safety', 'cost reduction'], metrics: ['patient satisfaction', 'readmission rate', 'wait time', 'cost per patient'], tone: 'professional_empathetic', openRate: '27%', triggers: ['Improve patient satisfaction by {points}', 'HIPAA compliant', 'Reduce readmissions by {%}'], requirements: ['HIPAA compliance mandatory', 'Focus on patient benefits', 'Include clinical evidence'], avoidTerms: ['guarantee', 'cure', 'breakthrough'], sensitivityLevel: 'high' },
  education: { emphasis: ['student outcomes', 'engagement', 'efficiency', 'accessibility'], metrics: ['graduation rate', 'engagement score', 'cost per student', 'satisfaction'], tone: 'supportive_inspirational', triggers: ['Improve student engagement by {%}', 'Save teachers {hours} per week', 'Boost graduation rates'], budgetConsiderations: 'Fiscal year based', decisionProcess: 'Committee-based', specialConsiderations: ['Emphasize ease of adoption', 'Show teacher testimonials', 'Highlight student success stories'] },
  manufacturing: { emphasis: ['efficiency', 'quality', 'safety', 'cost reduction', 'productivity'], metrics: ['OEE', 'defect rate', 'downtime', 'throughput', 'safety incidents'], tone: 'practical_data_driven', triggers: ['Reduce downtime by {%}', 'Improve OEE to {%}', 'Cut production costs by ${amount}'], focusOn: ['ROI calculations', 'implementation timeline', 'minimal disruption'], avoidTerms: ['disruptive', 'radical'], caseStudyRequired: true },
  technology: { emphasis: ['innovation', 'integration', 'developer experience', 'scalability'], metrics: ['deployment time', 'uptime', 'code quality', 'team velocity'], tone: 'peer_technical', avoidTerms: ['magic', 'seamless', 'easy'], preferTerms: ['powerful', 'flexible', 'built for'], technicalProof: true, openSourceFriendly: true, languageStyle: 'Technical but accessible', proofPreference: 'GitHub stars, technical benchmarks' }
};
