export interface BodyOptimizationRule { pattern: string; impact: string; category: string; usage?: string; }

export const BODY_OPTIMIZATION_RULES = {
  structure: { wordCount: { min: 50, max: 125, ideal: 75, impact: '51% response rate at 50-125 words' }, sentenceCount: { min: 6, max: 8, peak: 7, impact: '6.9% reply rate at 6-8 sentences' }, paragraphs: { max: 3, ideal: 2, structure: 'Opening (1-2 sent) + Value (2-3 sent) + CTA (1 sent)' }, readingGrade: { min: 8, max: 10, tool: 'Flesch-Kincaid Grade Level' } },
  openingLines: { effective: [ { pattern: "I'll be brief", impact: '+31% response', usage: 'Universal' }, { pattern: "I noticed {specific_observation}", impact: '+47% response', usage: 'Personalized' }, { pattern: "Quick question", impact: '+38% response', usage: 'Engaging' }, { pattern: "Not sure if you're the right person", impact: '+43% response', usage: 'Disarming' }, { pattern: "{Mutual_connection} suggested I reach out", impact: '+45% response', usage: 'Warm intro' }, { pattern: "I saw your {recent_activity}", impact: '+41% response', usage: 'Timely' } ], ineffective: [ { pattern: "I hope this finds you well", impact: '-18% response', reason: 'Generic filler' }, { pattern: "I wanted to reach out", impact: '-15% response', reason: 'Weak opening' }, { pattern: "I know you're busy", impact: '-22% response', reason: 'Negative framing' }, { pattern: "Sorry to bother you", impact: '-25% response', reason: 'Apologetic' }, { pattern: "Allow me to introduce myself", impact: '-20% response', reason: 'Self-focused' } ] },
  sentenceStructure: { distribution: { short: { percentage: 40, words: '5-10', purpose: 'Clarity & punch' }, medium: { percentage: 40, words: '11-20', purpose: 'Information delivery' }, long: { percentage: 20, words: '21+', purpose: 'Complex ideas only' } }, voiceRatio: { active: 80, passive: 20, example: 'We can help → Can help (active) vs Results were achieved (passive)' } },
  wordChoice: { powerWords: [ { word: 'because', impact: '+34% compliance', usage: 'Reason-giving' }, { word: 'imagine', impact: '+28% engagement', usage: 'Visualization' }, { word: 'proven', impact: '+31% trust', usage: 'Credibility' }, { word: 'exclusive', impact: '+22% interest', usage: 'Scarcity' }, { word: 'transform', impact: '+26% aspiration', usage: 'Change promise' } ], actionVerbs: ['achieve', 'boost', 'eliminate', 'accelerate', 'optimize', 'streamline', 'unlock', 'maximize'], sensoryWords: ['see', 'hear', 'feel', 'picture', 'visualize', 'discover', 'notice', 'experience'], weakWords: ['maybe', 'perhaps', 'hopefully', 'try', 'think', 'just', 'actually', 'really', 'very', 'stuff'] },
  paragraphStructure: { first: { sentences: '1-2 max', purpose: 'Hook & context', wordCount: '15-25' }, middle: { sentences: '2-3', purpose: 'Value proposition', wordCount: '30-50', placement: 'Social proof here' }, last: { sentences: '1', purpose: 'Clear CTA', wordCount: '10-15' }, formatting: { bulletPoints: 'Use for 3+ items only', whiteSpace: 'Critical for scannability', bold: 'One key metric only', links: 'Maximum 1 per email' } },
  credibilityMarkers: { specificNumbers: { impact: '37% more credible than vague claims', examples: ['increased revenue by 34%', 'saved 2.5 hours daily', '87 companies'] }, socialProof: { placement: 'Third paragraph ideal', types: ['client logos', 'testimonials', 'case studies', 'data points'], impact: '+28% trust' } },
  emotionalTriggers: { fearOfMissing: { phrases: ['limited availability', 'before', 'exclusive'], usage: 'Scarcity messaging' }, curiosity: { phrases: ['discover', 'secret', 'reveal'], usage: 'Knowledge gaps' }, belonging: { phrases: ['join', 'community', 'peers'], usage: 'Social connection' }, aspiration: { phrases: ['transform', 'achieve', 'elevate'], usage: 'Growth mindset' } },
  persuasionFrameworks: { problemAgitateSolve: { structure: 'Problem → Agitate → Solve', wordAllocation: '20% → 30% → 50%' }, beforeAfterBridge: { structure: 'Current state → Future state → How to get there', wordAllocation: '30% → 30% → 40%' }, starChainHook: { structure: 'Star (big idea) → Chain (proof) → Hook (CTA)', wordAllocation: '25% → 50% → 25%' } },
  mobileOptimization: { lineLength: '50-60 characters max', paragraphBreaks: 'Every 2-3 sentences', fontSize: '14px minimum', ctaPlacement: 'Above the fold', scrollDepth: '80% read first screen only' }
};
