import { BODY_OPTIMIZATION_RULES } from './constants';

export function scoreEmailBody(body: string): { score: number; improvements: string[]; strengths: string[]; metrics: { wordCount: number; sentenceCount: number; paragraphCount: number; readabilityScore: number } } {
  let score = 50; const improvements: string[] = []; const strengths: string[] = []; const words = body.split(/\s+/).filter(w => w.length > 0); const wordCount = words.length; const sentences = body.split(/[.!?]+/).filter(s => s.trim().length > 0); const sentenceCount = sentences.length; const paragraphs = body.split(/\n\n+/).filter(p => p.trim().length > 0); const paragraphCount = paragraphs.length;
  const avgWordsPerSentence = wordCount / Math.max(sentenceCount, 1); const avgSyllablesPerWord = 1.5; const readabilityGrade = 0.39 * avgWordsPerSentence + 11.8 * avgSyllablesPerWord - 15.59;
  const optimal = BODY_OPTIMIZATION_RULES.structure.wordCount; if (wordCount >= optimal.min && wordCount <= optimal.max) { score += 20; strengths.push(`Optimal length: ${wordCount} words`); } else if (wordCount > optimal.max) { score -= 10; improvements.push(`Reduce to ${optimal.ideal} words (currently ${wordCount})`); } else if (wordCount < optimal.min) { score -= 5; improvements.push(`Expand to at least ${optimal.min} words`); }
  const sentOptimal = BODY_OPTIMIZATION_RULES.structure.sentenceCount; if (sentenceCount >= sentOptimal.min && sentenceCount <= sentOptimal.max) { score += 15; strengths.push(`Good sentence count: ${sentenceCount}`); } else { improvements.push(`Aim for ${sentOptimal.peak} sentences`); }
  const powerWords = BODY_OPTIMIZATION_RULES.wordChoice.powerWords; let powerWordCount = 0; powerWords.forEach(({ word }) => { if (body.toLowerCase().includes(word)) { powerWordCount++; score += 3; } }); if (powerWordCount > 0) { strengths.push(`Contains ${powerWordCount} power words`); } else { improvements.push('Add power words: because, imagine, proven'); }
  const weakWords = BODY_OPTIMIZATION_RULES.wordChoice.weakWords; const foundWeak = weakWords.filter(word => body.toLowerCase().includes(word)); if (foundWeak.length > 0) { score -= foundWeak.length * 2; improvements.push(`Remove weak words: ${foundWeak.join(', ')}`); }
  if (body.includes('%') || /\d+/.test(body)) { score += 10; strengths.push('Contains specific metrics'); } else { improvements.push('Add specific numbers/percentages'); }
  const ctaIndicators = ['worth', 'interested', 'chat', 'discuss', 'explore', '?']; const hasCTA = ctaIndicators.some(indicator => body.toLowerCase().includes(indicator)); if (hasCTA) { score += 10; strengths.push('Clear call-to-action present'); } else { improvements.push('Add clear CTA question'); }
  if (readabilityGrade >= 8 && readabilityGrade <= 10) { score += 5; strengths.push('Good readability level'); } else if (readabilityGrade > 10) { improvements.push('Simplify language (grade 8-10)'); }
  return { score: Math.min(100, Math.max(0, score)), improvements, strengths, metrics: { wordCount, sentenceCount, paragraphCount, readabilityScore: Math.round(readabilityGrade * 10) / 10 } };
}
