import { composeMultipartEmail, composeReplyEmail } from '../deliverability/email-composer';
import { getUncachableGmailClient } from './tokens';

export async function sendEmail(userId: number, to: string, subject: string, body: string, options?: { htmlBody?: string; replyTo?: string; unsubscribeUrl?: string }) {
  const gmail = await getUncachableGmailClient(userId); const message = composeMultipartEmail({ to, subject, textBody: body, htmlBody: options?.htmlBody, replyTo: options?.replyTo, unsubscribeUrl: options?.unsubscribeUrl }); const encodedMessage = Buffer.from(message).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); const result = await gmail.users.messages.send({ userId: 'me', requestBody: { raw: encodedMessage } }); return { messageId: result.data.id, threadId: result.data.threadId };
}

export async function sendReplyInThread(userId: number, threadId: string, to: string, subject: string, body: string, options?: { htmlBody?: string; replyTo?: string; originalMessageId?: string }) {
  const gmail = await getUncachableGmailClient(userId); const senderEmail = (await gmail.users.getProfile({ userId: 'me' })).data.emailAddress || ''; let headers: any = {}; if (options?.originalMessageId) { try { const originalMessage = await gmail.users.messages.get({ userId: 'me', id: options.originalMessageId, format: 'metadata', metadataHeaders: ['Message-ID'] }); const messageIdHeader = originalMessage.data.payload?.headers?.find(h => h.name === 'Message-ID'); if (messageIdHeader?.value) { headers['In-Reply-To'] = messageIdHeader.value; headers['References'] = messageIdHeader.value; } } catch (e) { console.log('Could not fetch original message headers for reply'); } } const message = composeReplyEmail({ to, subject: subject.startsWith('Re:') ? subject : `Re: ${subject}`, textBody: body, htmlBody: options?.htmlBody, replyTo: options?.replyTo, from: senderEmail, inReplyTo: headers['In-Reply-To'], references: headers['References'] }); const encodedMessage = Buffer.from(message).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); const result = await gmail.users.messages.send({ userId: 'me', requestBody: { raw: encodedMessage, threadId: threadId } }); return { messageId: result.data.id, threadId: result.data.threadId };
}
