// Manual questionnaire configuration
// 27 questions across 7 sections for companies without online presence

import type { QuestionnaireSection } from './types';

export const manualQuestionnaire: QuestionnaireSection[] = [
    {
        id: 'business_identity',
        title: 'Business Identity',
        description: 'Tell us about your company',
        questions: [
            {
                id: 'q1_company_name',
                field: 'companyName',
                question: 'What is your company name?',
                type: 'short_answer',
                placeholder: 'Enter your official business name',
                required: true,
            },
            {
                id: 'q2_business_type',
                field: 'businessType',
                question: 'What type of business are you?',
                type: 'single_select',
                options: [
                    'B2B (We sell to other businesses)',
                    'B2C (We sell to consumers)',
                    'Both B2B and B2C',
                    'Non-profit / Organization',
                ],
                required: true,
            },
            {
                id: 'q3_industry',
                field: 'industry',
                question: 'What industry is your business in?',
                type: 'single_select',
                options: [
                    'Technology / Software / SaaS',
                    'Professional Services (Consulting, Legal, Accounting)',
                    'Healthcare / Medical / Wellness',
                    'Real Estate / Property Management',
                    'Financial Services / Insurance',
                    'Marketing / Advertising / Creative',
                    'E-commerce / Retail',
                    'Manufacturing / Industrial',
                    'Construction / Trades',
                    'Education / Training / Coaching',
                    'Hospitality / Food Service',
                    'Other',
                ],
                required: true,
            },
            {
                id: 'q4_years_in_business',
                field: 'yearsInBusiness',
                question: 'How long have you been in business?',
                type: 'single_select',
                options: [
                    'Less than 1 year',
                    '1-2 years',
                    '3-5 years',
                    '5-10 years',
                    '10+ years',
                ],
                required: false,
            },
            {
                id: 'q5_employee_count',
                field: 'employeeCount',
                question: 'How many employees does your company have?',
                type: 'single_select',
                options: [
                    'Just me (Solopreneur)',
                    '2-5 employees',
                    '6-20 employees',
                    '21-50 employees',
                    '51-200 employees',
                    '200+ employees',
                ],
                required: false,
            },
        ],
    },
    {
        id: 'products_services',
        title: 'Products & Services',
        description: 'What you offer',
        questions: [
            {
                id: 'q6_business_description',
                field: 'businessDescription',
                question: 'In one sentence, what does your company do?',
                type: 'short_answer',
                placeholder: 'Example: "We help small businesses automate their accounting and invoicing"',
                helpText: 'Keep it simple and clear - this helps us understand your core offering',
                required: true,
            },
            {
                id: 'q7_products_services',
                field: 'productsServices',
                question: 'What are your main products or services?',
                type: 'short_answer',
                placeholder: 'List 2-5 of your core offerings, separated by commas',
                helpText: 'Example: "Monthly bookkeeping, Tax preparation, CFO consulting, QuickBooks setup"',
                required: true,
            },
            {
                id: 'q8_pricing_model',
                field: 'pricingModel',
                question: 'What is your pricing model?',
                type: 'multi_select',
                options: [
                    'Monthly subscription/retainer',
                    'One-time projects',
                    'Hourly billing',
                    'Per-unit pricing',
                    'Custom/enterprise pricing',
                    'Free tier with paid upgrades',
                ],
                required: false,
            },
            {
                id: 'q9_deal_size',
                field: 'typicalDealSize',
                question: "What's your typical deal size?",
                type: 'single_select',
                options: [
                    'Under $100',
                    '$100 - $500',
                    '$500 - $2,000',
                    '$2,000 - $10,000',
                    '$10,000 - $50,000',
                    '$50,000+',
                    'Varies widely',
                ],
                required: false,
            },
        ],
    },
    {
        id: 'target_customers',
        title: 'Target Customers',
        description: 'Who you serve',
        questions: [
            {
                id: 'q10_ideal_customer',
                field: 'idealCustomerDescription',
                question: 'Who is your ideal customer?',
                type: 'short_answer',
                placeholder: 'Describe in detail who benefits most from your product/service',
                helpText: 'Example: "Marketing managers at mid-sized B2B tech companies who struggle with lead generation"',
                required: true,
            },
            {
                id: 'q11_job_titles',
                field: 'targetJobTitles',
                question: 'What job titles do you typically sell to?',
                type: 'short_answer',
                placeholder: 'Example: "CEO, Founder, Marketing Director, VP of Sales"',
                required: false,
            },
            {
                id: 'q12_target_industries',
                field: 'targetIndustries',
                question: 'What industries are your ideal customers in?',
                type: 'multi_select_with_other',
                options: [
                    'Same as my industry',
                    'Technology / Software',
                    'Healthcare',
                    'Financial Services',
                    'Professional Services',
                    'E-commerce / Retail',
                    'Manufacturing',
                    'Real Estate',
                    'Any industry',
                ],
                required: false,
            },
            {
                id: 'q13_company_sizes',
                field: 'targetCompanySizes',
                question: 'What size companies do you work with best?',
                type: 'multi_select',
                options: [
                    'Individuals / Solopreneurs',
                    'Startups (1-10 employees)',
                    'Small Business (11-50 employees)',
                    'Mid-Market (51-500 employees)',
                    'Enterprise (500+ employees)',
                ],
                required: false,
            },
            {
                id: 'q14_geographies',
                field: 'targetGeographies',
                question: 'What geographic areas do you serve?',
                type: 'multi_select_with_other',
                options: [
                    'Local only (city/metro area)',
                    'Regional (state/province)',
                    'National (one country)',
                    'North America',
                    'International / Global',
                ],
                required: false,
            },
        ],
    },
    {
        id: 'value_proposition',
        title: 'Value Proposition',
        description: 'Why customers choose you',
        questions: [
            {
                id: 'q15_problem_solved',
                field: 'problemSolved',
                question: 'What main problem does your product/service solve?',
                type: 'short_answer',
                placeholder: 'What pain did your customers have before they found you?',
                helpText: 'Example: "Small business owners were spending 10+ hours/week on bookkeeping instead of growing their business"',
                required: true,
            },
            {
                id: 'q16_differentiator',
                field: 'uniqueDifferentiator',
                question: 'What makes you different from competitors?',
                type: 'short_answer',
                placeholder: 'Why do customers choose YOU over alternatives?',
                helpText: 'Example: "We\'re the only CRM that integrates with all major accounting software"',
                required: true,
            },
            {
                id: 'q17_results',
                field: 'typicalResults',
                question: 'What results do your customers typically achieve?',
                type: 'short_answer',
                placeholder: 'Be specific with numbers if possible',
                helpText: 'Example: "Clients save an average of 15 hours/week and reduce accounting errors by 90%"',
                required: false,
            },
            {
                id: 'q18_social_proof',
                field: 'notableClients',
                question: 'Do you have any notable clients, case studies, or testimonials?',
                type: 'short_answer',
                placeholder: 'List any recognizable clients, success stories, or social proof',
                required: false,
            },
        ],
    },
    {
        id: 'sales_process',
        title: 'Sales Process',
        description: 'How you close deals',
        questions: [
            {
                id: 'q19_sales_cycle',
                field: 'salesCycleLength',
                question: 'How long is your typical sales cycle?',
                type: 'single_select',
                options: [
                    'Same day (impulse buy)',
                    '1-7 days',
                    '1-2 weeks',
                    '2-4 weeks',
                    '1-3 months',
                    '3-6 months',
                    '6+ months',
                ],
                required: false,
            },
            {
                id: 'q20_objections',
                field: 'commonObjections',
                question: 'What concerns do prospects typically have before buying?',
                type: 'multi_select_with_other',
                options: [
                    'Price is too high',
                    'Not sure it will work for them',
                    'Need to talk to partner/team/boss',
                    'Already using a competitor',
                    'Timing isn\'t right',
                    'Don\'t fully understand the offering',
                    'Worried about implementation/onboarding',
                    'Need more proof/references',
                ],
                required: false,
            },
            {
                id: 'q21_challenges',
                field: 'currentChallenges',
                question: "What's your current biggest challenge in sales/marketing?",
                type: 'short_answer',
                placeholder: 'What are you struggling with most when getting new customers?',
                required: false,
            },
        ],
    },
    {
        id: 'brand_voice',
        title: 'Brand Voice',
        description: 'How you communicate',
        questions: [
            {
                id: 'q22_personality',
                field: 'brandPersonality',
                question: "How would you describe your brand's personality?",
                type: 'multi_select',
                options: [
                    'Professional & Corporate',
                    'Friendly & Approachable',
                    'Expert & Authoritative',
                    'Innovative & Cutting-edge',
                    'Casual & Conversational',
                    'Bold & Confident',
                    'Warm & Caring',
                    'Fun & Playful',
                    'Luxury & Premium',
                    'Down-to-earth & Practical',
                ],
                maxSelections: 3,
                helpText: 'Pick up to 3 that best describe your brand',
                required: false,
            },
            {
                id: 'q23_formality',
                field: 'formalityLevel',
                question: 'How formal should your communication be?',
                type: 'single_select',
                options: [
                    'Very formal (Dear Mr./Ms., Regards, etc.)',
                    'Professional but friendly (Hi [Name], Best, etc.)',
                    'Casual and conversational (Hey [Name], Cheers, etc.)',
                    'Depends on the recipient/context',
                ],
                required: false,
            },
            {
                id: 'q24_phrases_use',
                field: 'phrasesToUse',
                question: 'Are there any words or phrases you ALWAYS use?',
                type: 'short_answer',
                placeholder: 'Taglines, key terms, or phrases that represent your brand',
                required: false,
            },
            {
                id: 'q25_phrases_avoid',
                field: 'phrasesToAvoid',
                question: 'Are there any words or phrases you NEVER use?',
                type: 'short_answer',
                placeholder: "Terms that don't fit your brand or industry",
                required: false,
            },
        ],
    },
    {
        id: 'final_details',
        title: 'Final Details',
        description: 'Wrapping up',
        questions: [
            {
                id: 'q26_desired_action',
                field: 'desiredLeadAction',
                question: 'What would you like leads to do after reading your message?',
                type: 'multi_select',
                options: [
                    'Book a call/meeting',
                    'Reply to the email',
                    'Visit our website',
                    'Sign up for a free trial',
                    'Request a quote',
                    'Download a resource',
                ],
                required: false,
            },
            {
                id: 'q27_additional',
                field: 'additionalNotes',
                question: 'Anything else we should know about your business?',
                type: 'short_answer',
                placeholder: 'Any additional context that would help us represent you accurately',
                required: false,
            },
        ],
    },
];

export function getManualQuestionnaire(): QuestionnaireSection[] {
    return manualQuestionnaire;
}

export function getTotalQuestionCount(): number {
    return manualQuestionnaire.reduce((sum, section) => sum + section.questions.length, 0);
}

export function getRequiredQuestionCount(): number {
    return manualQuestionnaire.reduce(
        (sum, section) => sum + section.questions.filter(q => q.required).length,
        0
    );
}
