import { timezoneOffsets } from './mappings';

function getTimezoneOffset(timezone: string): number { return timezoneOffsets[timezone] || -300; }

export function calculateOptimalSendTime(contactTimezone: string | null, preferredTime: string | null): Date { const now = new Date(); const timezone = contactTimezone || "America/New_York"; const time = preferredTime || "09:30"; try { const [hours, minutes] = time.split(':').map(Number); const formatter = new Intl.DateTimeFormat('en-US', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit', hour12: false }); const parts = formatter.formatToParts(now); const year = parseInt(parts.find(p => p.type === 'year')?.value || '2024'); const month = parseInt(parts.find(p => p.type === 'month')?.value || '1') - 1; const day = parseInt(parts.find(p => p.type === 'day')?.value || '1'); const targetDateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}T${time}:00`; const offset = getTimezoneOffset(timezone); const targetDate = new Date(targetDateStr); targetDate.setMinutes(targetDate.getMinutes() - offset); if (targetDate <= now) targetDate.setDate(targetDate.getDate() + 1); return targetDate; } catch (error) { console.error(`[Timezone] Error calculating optimal send time:`, error); const fallback = new Date(); fallback.setHours(fallback.getHours() + 1); return fallback; } }

export function isBusinessHours(date: Date, timezone: string): boolean { try { const formatter = new Intl.DateTimeFormat('en-US', { timeZone: timezone, hour: 'numeric', hour12: false, weekday: 'short' }); const parts = formatter.formatToParts(date); const hour = parseInt(parts.find(p => p.type === 'hour')?.value || '12'); const weekday = parts.find(p => p.type === 'weekday')?.value; if (weekday === 'Sat' || weekday === 'Sun') return false; return hour >= 8 && hour < 18; } catch (error) { console.error(`[Timezone] Error checking business hours:`, error); return true; } }

export function getNextBusinessDaySendTime(timezone: string): Date { const now = new Date(); let targetDate = new Date(now); targetDate.setHours(9, 30, 0, 0); if (now.getHours() >= 18) targetDate.setDate(targetDate.getDate() + 1); while (targetDate.getDay() === 0 || targetDate.getDay() === 6) targetDate.setDate(targetDate.getDate() + 1); return targetDate; }
