export const DIRECTNESS_RULEBOOK: Record<number, string | null> = {
  1: `DIRECTNESS: Very Indirect (Level 1)\nBuild extensive context before reaching any point.\nSTRUCTURE: Elaborate background → gradual build → soft suggestion\nDO: Provide thorough context, use hedging language, be tentative\nDON'T: State the ask directly, be blunt, or rush to the point\nEXAMPLE: "I hope you're well. I've been reflecting on some thoughts from our previous discussions, and I was wondering if perhaps, when you have a moment..."`,
  2: `DIRECTNESS: Quite Indirect (Level 2)\nProvide substantial context before the main point.\nSTRUCTURE: Background → context → soft lead-in → gentle ask\nDO: Build up to the point gradually, use polite hedging\nDON'T: Be abrupt or lead with the ask\nEXAMPLE: "I wanted to share some context on this first. After reviewing everything, I was hoping we might discuss..."`,
  3: `DIRECTNESS: Moderately Indirect (Level 3)\nProvide reasonable context before getting to the point.\nSTRUCTURE: Brief context → build-up → the ask\nDO: Give background before asking, ease into requests\nDON'T: Open with demands or skip context entirely\nEXAMPLE: "Thanks for your time yesterday. Building on what we discussed, I was wondering if you'd be open to..."`,
  4: null,
  5: null,
  6: null,
  7: `DIRECTNESS: Fairly Direct (Level 7)\nGet to the point quickly with minimal preamble.\nSTRUCTURE: Brief opener → main point → supporting detail\nDO: Lead with the key message, keep context minimal\nDON'T: Bury the lead or over-explain\nEXAMPLE: "Quick ask: can you review this deck by Thursday? It's for the client meeting Friday morning."`,
  8: `DIRECTNESS: Very Direct (Level 8)\nLead with the ask, add context only if necessary.\nSTRUCTURE: The ask → brief reason (optional)\nDO: Put the main point first, be efficient, respect their time\nDON'T: Over-explain or build up unnecessarily\nEXAMPLE: "Need your approval on the budget. Details attached. Let me know by EOD?"`,
  9: `DIRECTNESS: Extremely Direct (Level 9)\nState exactly what you need immediately.\nSTRUCTURE: The ask. Period.\nDO: Be maximally efficient, one clear point per email\nDON'T: Add fluff, over-explain, or pad with pleasantries\nEXAMPLE: "Can you call me in 10 minutes? It's about the Johnson account."`,
  10: `DIRECTNESS: Ultra Direct (Level 10)\nSingle-sentence precision. No context needed.\nSTRUCTURE: Just the essential ask. Nothing else.\nDO: Communicate in the absolute minimum words possible\nDON'T: Add any unnecessary words, context, or pleasantries\nEXAMPLE: "Call me now." or "Yes." or "Approved."`
};
