export const VARIANT_DIVERSITY_RULEBOOK: Record<number, string> = {
  1: `VARIANT DIVERSITY: Nearly Identical (Level 1)\nMake the 3 variants almost the same with only tiny word swaps.\nCHANGES ALLOWED: Synonym substitutions only (e.g., "great" vs "excellent")\nKEEP IDENTICAL: Structure, length, opening, closing, flow\nEXAMPLE: The variants read like the same email with minor word changes`,
  2: `VARIANT DIVERSITY: Minimal Variations (Level 2)\nMake the 3 variants very similar with small phrase variations.\nCHANGES ALLOWED: Slightly different word choices, minor sentence tweaks\nKEEP SIMILAR: Overall structure, length, tone, approach\nEXAMPLE: Same email structure with small wording differences`,
  3: `VARIANT DIVERSITY: Slight Differences (Level 3)\nMake the 3 variants similar but with noticeable small differences.\nCHANGES ALLOWED: Sentence rephrasing, slightly different openings\nKEEP SIMILAR: Core structure, length, and approach\nEXAMPLE: Same approach with slightly different sentence constructions`,
  4: `VARIANT DIVERSITY: Some Variation (Level 4)\nMake the 3 variants take slightly different angles on the same approach.\nCHANGES ALLOWED: Different sentence structures, varied emphasis on points\nKEEP SIMILAR: Overall approach, approximate length, core message\nEXAMPLE: Three takes on the same approach, each with its own sentence rhythm`,
  5: `VARIANT DIVERSITY: Moderate Variation (Level 5)\nMake the 3 variants noticeably different while keeping the same overall approach.\nCHANGES ALLOWED: Different opening hooks, varied sentence structures, different supporting points\nKEEP SIMILAR: Core ask, sender's voice, overall tone\nEXAMPLE: Each variant feels fresh but covers the same ground`,
  6: `VARIANT DIVERSITY: Notable Differences (Level 6)\nMake the 3 variants distinctly different in how they present the message.\nCHANGES ALLOWED: Different opening hooks, varied paragraph structures, different supporting points\nKEEP SIMILAR: Core ask, sender's voice, approximate length\nEXAMPLE: Each variant opens differently and builds the argument in a unique way`,
  7: `VARIANT DIVERSITY: Distinct Approaches (Level 7)\nMake the 3 variants take noticeably different approaches to the same goal.\nCHANGES ALLOWED: Different opening hooks, varied paragraph structure, different emphasis on benefits\nVARY: How the email is organized, which points are emphasized\nKEEP: Core ask, sender's voice, key message\nEXAMPLE: One variant leads with a question, another with a statement, another with context`,
  8: `VARIANT DIVERSITY: Different Angles (Level 8)\nMake the 3 variants emphasize different value propositions or benefits.\nCHANGES ALLOWED: Each variant can highlight a different benefit, use different hooks, vary length\nVARY: The persuasion angle, supporting arguments, opening strategy\nKEEP: Core ask, sender's authentic voice\nCONSTRAINT REMINDER: All variants MUST still honor user instructions, tone settings, and writing style.\nEXAMPLE: Variant A emphasizes time savings, Variant B emphasizes cost savings, Variant C emphasizes quality`,
  9: `VARIANT DIVERSITY: Alternate Strategies (Level 9)\nMake the 3 variants use distinctly different persuasion approaches.\nCHANGES ALLOWED: Different persuasion techniques (social proof vs curiosity vs direct value), different lengths, different structures\nVARY: The overall strategy, email length, level of detail\nKEEP: Core ask, sender's authentic voice\nCONSTRAINT REMINDER: High diversity does NOT mean ignoring constraints. If user said "keep it under 3 sentences" - ALL variants must honor that.\nEXAMPLE: Variant A uses social proof, Variant B creates curiosity, Variant C is direct value prop`,
  10: `VARIANT DIVERSITY: Completely Different (Level 10)\nMake the 3 variants feel like 3 different emails written for the same purpose.\nCHANGES ALLOWED: Different tones within the sender's range, different lengths (short/medium/long), different structures, different persuasion strategies\nVARY: Nearly everything except the core ask and sender's voice\nKEEP: The core ask/CTA must be the same, must still sound like the sender\nCRITICAL CONSTRAINT: Even at maximum diversity, user instructions are INVIOLABLE.\nEXAMPLE: One short and punchy, one detailed and comprehensive, one warm and relationship-focused`
};
