export const FORMALITY_RULEBOOK: Record<number, string | null> = {
  1: `FORMALITY: Ultra Casual (Level 1)\nWrite like texting a close friend.\nGREETINGS: "Hey!" or "Yo" or just dive in with no greeting\nCLOSINGS: "Later!" or "Cheers" or just your first name\nDO: Use abbreviations (gonna, wanna, btw), sentence fragments, casual punctuation\nDON'T: Use "Dear", full sentences everywhere, or any formal language\nEXAMPLE: "Hey! Quick thing - you free Tuesday? Wanna grab coffee and chat about that project?"`,
  2: `FORMALITY: Very Casual (Level 2)\nWrite like a Slack message to a friendly colleague.\nGREETINGS: "Hey [Name]" or "Hi!" \nCLOSINGS: "Thanks!" or "Cheers," or first name only\nDO: Use contractions always, short punchy sentences, exclamation marks okay\nDON'T: Use titles (Mr./Ms.), formal closings like "Sincerely", or stiff language\nEXAMPLE: "Hey Sarah! Just wanted to loop you in on this. Let me know what you think!"`,
  3: `FORMALITY: Casual (Level 3)\nWrite like a friendly email to someone you know.\nGREETINGS: "Hi [Name]," or "Hey [Name],"\nCLOSINGS: "Thanks," or "Best," or "Cheers,"\nDO: Use contractions freely, conversational tone, personality shows through\nDON'T: Use "Dear", overly formal vocabulary, or rigid sentence structures\nEXAMPLE: "Hi Mike, Hope you're doing well! I wanted to follow up on our conversation from last week."`,
  4: null,
  5: null,
  6: null,
  7: `FORMALITY: Professional (Level 7)\nWrite like a business email to someone you respect.\nGREETINGS: "Hello [Name]," or "Dear [Name],"\nCLOSINGS: "Best regards," or "Thank you,"\nDO: Full sentences, proper grammar, polished vocabulary\nDON'T: Use slang, excessive exclamation marks, or overly casual language\nEXAMPLE: "Hello Dr. Smith, Thank you for taking the time to meet with me yesterday. I wanted to share some additional thoughts on our discussion."`,
  8: `FORMALITY: Quite Formal (Level 8)\nWrite like a business letter to a senior executive.\nGREETINGS: "Dear [Name]," or "Dear [Title] [LastName],"\nCLOSINGS: "Best regards," or "Sincerely," with full name\nDO: Use complete sentences, professional vocabulary, proper titles\nDON'T: Use contractions, casual language, or assume familiarity\nEXAMPLE: "Dear Ms. Johnson, I am writing to follow up on our previous correspondence regarding the Q3 projections."`,
  9: `FORMALITY: Very Formal (Level 9)\nWrite like a letter to a board of directors.\nGREETINGS: "Dear [Title] [LastName]," or "Dear Members of the Board,"\nCLOSINGS: "Respectfully," or "Sincerely," with full name and title\nDO: Use deferential language, passive constructions where appropriate, elevated vocabulary\nDON'T: Use any contractions, casual phrases, or assume familiarity\nEXAMPLE: "Dear Chairman Williams, I am honored to present the findings of our comprehensive review for your consideration."`,
  10: `FORMALITY: Ultra Formal (Level 10)\nWrite like formal diplomatic correspondence.\nGREETINGS: "Dear Honorable [Title]," or "To Whom It May Concern,"\nCLOSINGS: "Respectfully yours," or "I remain, your humble servant,"\nDO: Use the most deferential language possible, ornate phrasing, complete formality\nDON'T: Use any casual language whatsoever, never assume familiarity\nEXAMPLE: "Dear Esteemed Members of the Committee, It is with the utmost respect that I present before you the matter requiring your distinguished consideration."`
};
