import type { EnrichmentResult } from './types';
import { extractIndustry, extractCompanySize, extractRevenue, extractNews, extractLocation, mapEmployeeCount } from './helpers';

export async function enrichWithGoogle(contact: any): Promise<EnrichmentResult | null> { const apiKey = process.env.GOOGLE_API_KEY; const searchEngineId = process.env.GOOGLE_SEARCH_ENGINE_ID; if (!apiKey || !searchEngineId) return null; try { const query = `${contact.company} company industry revenue size`; const url = `https://www.googleapis.com/customsearch/v1?key=${apiKey}&cx=${searchEngineId}&q=${encodeURIComponent(query)}`; const response = await fetch(url); if (!response.ok) { console.error(`[Enrichment] Google API error: ${response.statusText}`); return null; } const data = await response.json(); const snippets = data.items?.slice(0, 3).map((item: any) => item.snippet).join(" ") || ""; return { industry: extractIndustry(snippets), companySize: extractCompanySize(snippets), companyRevenue: extractRevenue(snippets), recentNews: extractNews(snippets), location: extractLocation(snippets), source: "google", confidence: 6 }; } catch (error) { console.error(`[Enrichment] Google enrichment error:`, error); return null; } }

export async function enrichWithClearbit(contact: any): Promise<EnrichmentResult | null> { const apiKey = process.env.CLEARBIT_API_KEY; if (!apiKey) return null; try { const domain = contact.email.split('@')[1]; const url = `https://company.clearbit.com/v2/companies/find?domain=${domain}`; const response = await fetch(url, { headers: { 'Authorization': `Bearer ${apiKey}` } }); if (!response.ok) { console.error(`[Enrichment] Clearbit API error: ${response.statusText}`); return null; } const data = await response.json(); return { industry: data.category?.industry, companySize: mapEmployeeCount(data.metrics?.employees), companyRevenue: data.metrics?.annualRevenue?.toString(), location: `${data.geo?.city}, ${data.geo?.state}`, recentNews: data.description, source: "clearbit", confidence: 8 }; } catch (error) { console.error(`[Enrichment] Clearbit enrichment error:`, error); return null; } }

export async function enrichWithApollo(contact: any): Promise<EnrichmentResult | null> { const apiKey = process.env.APOLLO_API_KEY; if (!apiKey) return null; try { const domain = contact.email.split('@')[1]; const url = 'https://api.apollo.io/v1/organizations/enrich'; const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', 'X-Api-Key': apiKey }, body: JSON.stringify({ domain }) }); if (!response.ok) { console.error(`[Enrichment] Apollo API error: ${response.statusText}`); return null; } const data = await response.json(); const org = data.organization; return { industry: org.primary_industry || org.industry, companySize: mapEmployeeCount(org.estimated_num_employees), companyRevenue: org.annual_revenue?.toString(), location: `${org.city}, ${org.state}`, recentNews: org.short_description, source: "apollo", confidence: 9 }; } catch (error) { console.error(`[Enrichment] Apollo enrichment error:`, error); return null; } }

export async function enrichWithFullContact(contact: any): Promise<EnrichmentResult | null> { const apiKey = process.env.FULLCONTACT_API_KEY; if (!apiKey) return null; try { const url = 'https://api.fullcontact.com/v3/company.enrich'; const response = await fetch(url, { method: 'POST', headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ domain: contact.email.split('@')[1] }) }); if (!response.ok) { console.error(`[Enrichment] FullContact API error: ${response.statusText}`); return null; } const data = await response.json(); const company = data.details; return { industry: company.category, companySize: mapEmployeeCount(company.employees), location: `${company.locality}, ${company.region}`, recentNews: company.bio, source: "fullcontact", confidence: 8 }; } catch (error) { console.error(`[Enrichment] FullContact enrichment error:`, error); return null; } }
