import { Request, Response } from 'express';
import { z } from 'zod';
import * as calendarService from '../../services/calendar-service';
import { db } from '../../db';
import { calendarEvents } from '../../../shared/schema';
import { eq } from 'drizzle-orm';

export async function createEvent(req: Request, res: Response) { try { if (!req.user) return res.status(401).json({ error: 'Unauthorized' }); const eventSchema = z.object({ contactId: z.number().optional(), summary: z.string(), description: z.string().optional(), location: z.string().optional(), startTime: z.string(), endTime: z.string(), timeZone: z.string().optional(), attendees: z.array(z.object({ email: z.string().email(), displayName: z.string().optional() })).optional(), enableGoogleMeet: z.boolean().optional() }); const data = eventSchema.parse(req.body); const googleEvent = await calendarService.createCalendarEvent(req.user.id, { summary: data.summary, description: data.description, location: data.location, start: { dateTime: data.startTime, timeZone: data.timeZone || 'America/New_York' }, end: { dateTime: data.endTime, timeZone: data.timeZone || 'America/New_York' }, attendees: data.attendees, conferenceData: data.enableGoogleMeet ? { createRequest: { requestId: `meet-${Date.now()}`, conferenceSolutionKey: { type: 'hangoutsMeet' } } } : undefined }); const [dbEvent] = await db.insert(calendarEvents).values({ userId: req.user.id, contactId: data.contactId, googleEventId: googleEvent.id, summary: data.summary, description: data.description, location: data.location, startTime: new Date(data.startTime), endTime: new Date(data.endTime), timeZone: data.timeZone || 'America/New_York', attendees: data.attendees || [], conferenceLink: googleEvent.hangoutLink || null, status: 'confirmed' }).returning(); res.json(dbEvent); } catch (error: any) { console.error('Error creating calendar event:', error); res.status(400).json({ error: error.message || 'Failed to create calendar event' }); } }

export async function listEvents(req: Request, res: Response) { try { if (!req.user) return res.status(401).json({ error: 'Unauthorized' }); const querySchema = z.object({ timeMin: z.string(), timeMax: z.string() }); const { timeMin, timeMax } = querySchema.parse(req.query); const events = await calendarService.listCalendarEvents(req.user.id, timeMin, timeMax); res.json(events); } catch (error: any) { console.error('Error listing calendar events:', error); res.status(400).json({ error: error.message || 'Failed to list calendar events' }); } }

export async function deleteEvent(req: Request, res: Response) { try { if (!req.user) return res.status(401).json({ error: 'Unauthorized' }); const eventId = req.params.eventId; const [event] = await db.select().from(calendarEvents).where(eq(calendarEvents.id, parseInt(eventId))); if (!event || event.userId !== req.user.id) return res.status(404).json({ error: 'Event not found' }); if (event.googleEventId) await calendarService.deleteCalendarEvent(req.user.id, event.googleEventId); await db.delete(calendarEvents).where(eq(calendarEvents.id, parseInt(eventId))); res.json({ success: true }); } catch (error: any) { console.error('Error deleting calendar event:', error); res.status(400).json({ error: error.message || 'Failed to delete event' }); } }
