import { callOpenAIFast } from "../openai-client";
import type { IntentResult } from "./types";

export async function runFirstPassAnalysis(content: string): Promise<IntentResult> {
  const systemPrompt = `You are an email intent classifier (PASS 1). Analyze the prospect's reply and determine their intent.\n\nCRITICAL: You must be VERY CONSERVATIVE. Only classify as "booking" if the person is EXPLICITLY and CLEARLY saying YES to meeting.\n\nOutput JSON:\n- intentType: "booking", "interested", "question", "not_interested", "unsubscribe", "out_of_office", or "other"\n- confidence: 0-100 (be conservative - use 95+ only for crystal clear YES responses)\n- reasoning: brief explanation\n\nBOOKING examples (very high confidence):\n- "Yes, let's chat!" → booking, 97\n- "Sounds good, I'm free next week" → booking, 95\n- "Let's schedule a call" → booking, 96\n- "I'd love to discuss this" → booking, 93\n\nNOT BOOKING examples:\n- "Maybe, what's the pricing?" → question, 70\n- "Interesting, tell me more" → interested, 65\n- "Let me think about it" → interested, 55\n- "Yes but I'm traveling until next month" → interested, 70 (has constraint)`;
  try { const response = await callOpenAIFast([{ role: "system", content: systemPrompt }, { role: "user", content: `Analyze this reply:\n\n"${content}"` }], { responseFormat: { type: "json_object" }, maxTokens: 200 }); const parsed = JSON.parse(response); return { intentType: parsed.intentType || 'other', confidence: Math.min(100, Math.max(0, parsed.confidence || 50)), reasoning: parsed.reasoning || 'AI analysis' }; } catch (error) { console.error('[BulletproofIntent] Pass 1 error:', error); return { intentType: 'other', confidence: 0, reasoning: 'Error in first pass analysis' }; }
}

export async function runSecondPassAnalysis(content: string, pass1Result: IntentResult): Promise<IntentResult> {
  const systemPrompt = `You are an email intent VERIFIER (PASS 2). Your job is to DOUBLE-CHECK a previous classification.\n\nThe previous analysis classified this as: ${pass1Result.intentType} with ${pass1Result.confidence}% confidence.\nReasoning: ${pass1Result.reasoning}\n\nYour task: INDEPENDENTLY analyze the email and see if you agree. Look for:\n1. Sarcasm or irony that might be missed\n2. Hidden objections or constraints\n3. Politeness that might be mistaken for agreement\n4. Questions that indicate they're not ready to commit\n\nBe SKEPTICAL. If there's ANY doubt, lower the confidence significantly.\n\nOutput JSON:\n- intentType: your independent classification\n- confidence: your confidence level (be conservative)\n- reasoning: explain if you agree or disagree with Pass 1 and why`;
  try { const response = await callOpenAIFast([{ role: "system", content: systemPrompt }, { role: "user", content: `Verify this email classification:\n\n"${content}"` }], { responseFormat: { type: "json_object" }, maxTokens: 200 }); const parsed = JSON.parse(response); return { intentType: parsed.intentType || 'other', confidence: Math.min(100, Math.max(0, parsed.confidence || 50)), reasoning: parsed.reasoning || 'AI verification' }; } catch (error) { console.error('[BulletproofIntent] Pass 2 error:', error); return { intentType: 'other', confidence: 0, reasoning: 'Error in second pass verification' }; }
}
