export const STYLE_PROMPTS: Record<string, string> = {
  "professional-adult": `GOAL: Sound like a capable professional having a natural conversation. TRAITS: Confident but not arrogant. Clear but not robotic. Warm but not overly casual. SENTENCE RHYTHM: Vary between short punchy statements and slightly longer explanatory ones. AVOID: Jargon, filler words, excessive formality. SOUND LIKE: A smart colleague sharing useful information over coffee.`,
  "friendly-energetic": `GOAL: Sound genuinely excited about connecting, without being exhausting. TRAITS: Enthusiastic but measured. Personal but professional. Curious about them. SENTENCE RHYTHM: Mix excited short sentences with thoughtful longer ones. AVOID: ALL CAPS, multiple exclamation points, over-the-top praise. SOUND LIKE: That colleague everyone likes - upbeat but genuine.`,
  "executive-brief": `GOAL: Respect their time with laser-focused communication. TRAITS: Direct, substantive, no fluff. Every word earns its place. SENTENCE RHYTHM: Predominantly short. Occasionally medium for key points. AVOID: Warm-up sentences, small talk, hedging language. SOUND LIKE: A senior exec who values your time as much as theirs.`,
  "consultative": `GOAL: Position yourself as a peer who can help them think through problems. TRAITS: Insightful, questioning, collaborative. Curious about their specific situation. SENTENCE RHYTHM: Observation. Question. Insight. More curiosity. AVOID: Prescriptive advice, assumed solutions, lecturing. SOUND LIKE: A strategic advisor asking the right questions.`,
  "casual-authentic": `GOAL: Sound like a real person, not a sales email. TRAITS: Genuine, conversational, unpretentious. Slightly informal but still professional. SENTENCE RHYTHM: Natural speech patterns. Short. Then maybe a bit longer. Then back to short. AVOID: Corporate speak, templates, anything that "sounds like marketing." SOUND LIKE: A smart friend who happens to know something useful.`,
  "storytelling": `GOAL: Connect through narrative before getting to the point. TRAITS: Engaging, relatable, builds to an insight. Uses specific details. SENTENCE RHYTHM: Scene-setting. Build-up. The insight. The connection to them. AVOID: Long-winded stories, irrelevant details, losing the business purpose. SOUND LIKE: A great communicator who makes points through stories.`,
  "data-driven": `GOAL: Let the numbers make your case. TRAITS: Specific, evidence-based, analytical. But still human. SENTENCE RHYTHM: Claim. Evidence. Implication. Each flows from the last. AVOID: Made-up statistics, overwhelming with data, robotic tone. SOUND LIKE: An analyst who can explain findings clearly.`,
  "provocative": `GOAL: Challenge their thinking to earn a response. TRAITS: Bold, contrarian, thought-provoking. But respectful. SENTENCE RHYTHM: Challenge. Support. Bigger implication. Invitation to engage. AVOID: Being offensive, attacking them personally, empty provocation. SOUND LIKE: A thought leader who questions conventional wisdom.`,
  "humble-helpful": `GOAL: Lead with genuine value, not self-promotion. TRAITS: Generous, modest, focused on their needs. Specific help offered. SENTENCE RHYTHM: What I noticed about you. Something that might help. Low-key offer. AVOID: False modesty, martyrdom, burying the value. SOUND LIKE: Someone who genuinely wants to help, not just sell.`,
  "technical-precise": `GOAL: Communicate complex ideas clearly and accurately. TRAITS: Precise, structured, knowledgeable. Respects technical depth. SENTENCE RHYTHM: Problem. Solution step. Solution step. Result. AVOID: Oversimplifying, jargon without context, condescension. SOUND LIKE: Senior engineer explaining clearly.`,
};
